services:

  node1:
    build: .
    environment:
      - NODE_ID=${node_id1}
      - PRIVATE_KEY=${NODE1_PRIVATE_KEY}
      - PUBLIC_KEY=${NODE1_PUBLIC_KEY}


  node2:
    build: .
    environment:
      - NODE_ID=${node_id2}
      - PRIVATE_KEY=${NODE2_PRIVATE_KEY}
      - PUBLIC_KEY=${NODE2_PUBLIC_KEY}


  node3:
    build: .
    environment:
      - NODE_ID=${node_id3}
      - PRIVATE_KEY=${NODE3_PRIVATE_KEY}
      - PUBLIC_KEY=${NODE3_PUBLIC_KEY}
